# Basic
title: 欧耶
subtitle: 有之为利 无之为用
welcome_message: <p><a href="http://archiz.com" target="_blank">聊以为生</a></p><p><a href="http://cn.archiz.com" target="_blank">赖以为活</a></p>
description: 欧耶，来自中国现居温哥华，房屋建筑设计与建造相关工作。
creator: <a href="http://mkzg.com">@欧耶</a>

url: "http://mkzg.com"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 随笔
    description: olim 欧林木平时写的一些东西

# Navigation buttons in the front page.
nav:
    - {title: 摄影, description: olim平时拍的一些东西, url: 'http://mkzg.com/photo/'}
    - {title: 工程, description: olim做过的一些东西, url: 'http://project.mkzg.com'}
    # - {title: 联络, description: olim的一些联系方式, url: '/contact/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: mkzg
    # duoshuo:

# Social
social:
    weibo: #olimw
    facebook: #archiwei
    github:
    twitter: mkzg
    gplus: #107716023262945317060
    mail: william@mkzg.com
    linkedin:
    tumblr:
    youtube:
    instagram: #archiwei
    pinterest:

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
