# Basic
title: Archiwei 老韦
subtitle: 有之为利 无之为用
welcome_message: <p><a href="http://liangdesign.com" target="_blank">赖以为生的技能一</a></p><p><a href="http://yaju.ca" target="_blank">赖以为生的技能二</a></p>
description: Archiwei，来自中国，现居温哥华，一直和房屋建筑打交道。
creator: <a href="http://mkzg.com">@archiwei</a>

url: "http://mkzg.com"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 随笔
    description: 我写的一些东西

# Navigation buttons in the front page.
nav:
    - {title: 摄影, description: 我拍的一些东西, url: 'http://liangphoto.com'}
    - {title: 工程, description: 我做的一些东西, url: 'http://project.mkzg.com'}
    - {title: 联络, description: 我的一些联系方式, url: '/contact/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: mkzg
    # duoshuo:

# Social
social:
    weibo: olimw
    github: mkzg
    twitter: archwei
    gplus: 107716023262945317060
    mail: archiwei@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
